name: easy_budget
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  collection: ^1.18.0
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.4.10
  local_auth: ^2.1.8
  intl: ^0.18.1
  local_auth_ios: ^1.1.7
  local_auth_android: ^1.0.37
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: 3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
