// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDgAlhOxsJVQ8iZ8K5DSgv0CNnIKWDSRY',
    appId: '1:114990339231:web:d0f808d9e290d0c45afeaa',
    messagingSenderId: '114990339231',
    projectId: 'easybudget-c0d93',
    authDomain: 'easybudget-c0d93.firebaseapp.com',
    storageBucket: 'easybudget-c0d93.appspot.com',
    measurementId: 'G-QK9TBD2L7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZfm5io11FKBYAudLvWyKr_zOkiBpx7N0',
    appId: '1:114990339231:android:76e081b39941860c5afeaa',
    messagingSenderId: '114990339231',
    projectId: 'easybudget-c0d93',
    storageBucket: 'easybudget-c0d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgfI-yBgZbmzKAlqxt0r4B0-HKYK2q8Hk',
    appId: '1:114990339231:ios:b8fdfe6ef0a2f3ab5afeaa',
    messagingSenderId: '114990339231',
    projectId: 'easybudget-c0d93',
    storageBucket: 'easybudget-c0d93.appspot.com',
    iosBundleId: 'com.example.easyBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgfI-yBgZbmzKAlqxt0r4B0-HKYK2q8Hk',
    appId: '1:114990339231:ios:2ef3325c724f0ff55afeaa',
    messagingSenderId: '114990339231',
    projectId: 'easybudget-c0d93',
    storageBucket: 'easybudget-c0d93.appspot.com',
    iosBundleId: 'com.example.easyBudget.RunnerTests',
  );
}
